import { DataType } from './lib/types';

export const PATIENT_VISITS: DataType[] = [
  {
    location: 'Sequoia Hospital',
    administration: 'Pharmacy',
    medication: 'Albuterol',
    visit_time: '2024-01-17T00:06:21',
    duration: 66,
    medication_tolerance: 'Stable',
    pain_level: 1,
    blood_pressure: '135/88',
    nurse: {
      name: 'Michael Brown',
      profile_picture: 'https://api.dicebear.com/7.x/miniavs/svg?seed=0',
      specialty: 'Cardiac',
    },
  },
  {
    location: 'UCSF Medical Center',
    administration: 'In-home',
    medication: 'Lisinopril',
    visit_time: '2024-01-23T19:08:23',
    duration: 76,
    medication_tolerance: 'Improving',
    pain_level: 2,
    blood_pressure: '120/80',
    nurse: {
      name: 'Linda Taylor',
      profile_picture: 'https://api.dicebear.com/7.x/miniavs/svg?seed=1',
      specialty: 'Emergency',
    },
  },
  {
    location: 'San Mateo Medical Center',
    administration: 'Pharmacy',
    medication: 'Albuterol',
    visit_time: '2024-01-22T22:16:49',
    duration: 90,
    medication_tolerance: 'Worsening',
    pain_level: 3,
    blood_pressure: '115/75',
    nurse: {
      name: 'Mary Brown',
      profile_picture: 'https://api.dicebear.com/7.x/miniavs/svg?seed=2',
      specialty: 'Diabetes',
    },
  },
  {
    location: 'Stanford Health Care',
    administration: 'Pharmacy',
    medication: 'Omeprazole',
    visit_time: '2024-01-14T00:40:09',
    duration: 51,
    medication_tolerance: 'Stable',
    pain_level: 2,
    blood_pressure: '150/95',
    nurse: {
      name: 'John Miller',
      profile_picture: 'https://api.dicebear.com/7.x/miniavs/svg?seed=3',
      specialty: 'Cardiac',
    },
  },
  {
    location: 'Alta Bates Summit Medical Center',
    administration: 'In-home',
    medication: 'Metformin',
    visit_time: '2024-01-24T22:22:36',
    duration: 26,
    medication_tolerance: 'Stable',
    pain_level: 2,
    blood_pressure: '160/100',
    nurse: {
      name: 'Robert Miller',
      profile_picture: 'https://api.dicebear.com/7.x/miniavs/svg?seed=4',
      specialty: 'Psychiatric',
    },
  },
  {
    location: 'San Mateo Medical Center',
    administration: 'Pharmacy',
    medication: 'Amlodipine',
    visit_time: '2024-01-10T14:51:42',
    duration: 38,
    medication_tolerance: 'Worsening',
    pain_level: 3,
    blood_pressure: '180/110',
    nurse: {
      name: 'Mary Jones',
      profile_picture: 'https://api.dicebear.com/7.x/miniavs/svg?seed=5',
      specialty: 'Dermatology',
    },
  },
  {
    location: 'Santa Clara Valley Medical Center',
    administration: 'Hospital',
    medication: 'Amlodipine',
    visit_time: '2024-01-28T15:49:28',
    duration: 82,
    medication_tolerance: 'Improving',
    pain_level: 4,
    blood_pressure: '155/98',
    nurse: {
      name: 'James Moore',
      profile_picture: 'https://api.dicebear.com/7.x/miniavs/svg?seed=6',
      specialty: 'Orthopedic',
    },
  },
  {
    location: 'Alta Bates Summit Medical Center',
    administration: 'Hospital',
    medication: 'Losartan',
    visit_time: '2024-01-10T13:57:36',
    duration: 97,
    medication_tolerance: 'Improving',
    pain_level: 4,
    blood_pressure: '130/85',
    nurse: {
      name: 'Robert Brown',
      profile_picture: 'https://api.dicebear.com/7.x/miniavs/svg?seed=7',
      specialty: 'Emergency',
    },
  },
  {
    location: 'San Francisco General Hospital',
    administration: 'Pharmacy',
    medication: 'Albuterol',
    visit_time: '2024-01-11T12:23:22',
    duration: 112,
    medication_tolerance: 'Improving',
    pain_level: 5,
    blood_pressure: '125/82',
    nurse: {
      name: 'Jennifer Smith',
      profile_picture: 'https://api.dicebear.com/7.x/miniavs/svg?seed=8',
      specialty: 'Oncology',
    },
  },
  {
    location: 'Santa Clara Valley Medical Center',
    administration: 'In-home',
    medication: 'Simvastatin',
    visit_time: '2024-01-12T15:46:01',
    duration: 110,
    medication_tolerance: 'Worsening',
    pain_level: 2,
    blood_pressure: '170/105',
    nurse: {
      name: 'Jennifer Jones',
      profile_picture: 'https://api.dicebear.com/7.x/miniavs/svg?seed=9',
      specialty: 'Cardiac',
    },
  },
  {
    location: 'Santa Clara Valley Medical Center',
    administration: 'In-home',
    medication: 'Albuterol',
    visit_time: '2024-01-20T21:26:39',
    duration: 60,
    medication_tolerance: 'Stable',
    pain_level: 2,
    blood_pressure: '90/60',
    nurse: {
      name: 'William Brown',
      profile_picture: 'https://api.dicebear.com/7.x/miniavs/svg?seed=10',
      specialty: 'Cardiac',
    },
  },
  {
    location: 'John Muir Health',
    administration: 'Hospital',
    medication: 'Metformin',
    visit_time: '2024-01-24T09:12:46',
    duration: 102,
    medication_tolerance: 'Improving',
    pain_level: 1,
    blood_pressure: '110/70',
    nurse: {
      name: 'Jennifer Brown',
      profile_picture: 'https://api.dicebear.com/7.x/miniavs/svg?seed=11',
      specialty: 'Pediatric',
    },
  },
  {
    location: 'John Muir Health',
    administration: 'Pharmacy',
    medication: 'Metformin',
    visit_time: '2024-01-12T15:52:10',
    duration: 41,
    medication_tolerance: 'Stable',
    pain_level: 1,
    blood_pressure: '140/90',
    nurse: {
      name: 'William Miller',
      profile_picture: 'https://api.dicebear.com/7.x/miniavs/svg?seed=12',
      specialty: 'Diabetes',
    },
  },
  {
    location: 'John Muir Health',
    administration: 'Pharmacy',
    medication: 'Lisinopril',
    visit_time: '2024-01-12T01:05:39',
    duration: 46,
    medication_tolerance: 'Improving',
    pain_level: 2,
    blood_pressure: '100/65',
    nurse: {
      name: 'John Williams',
      profile_picture: 'https://api.dicebear.com/7.x/miniavs/svg?seed=13',
      specialty: 'Pediatric',
    },
  },
  {
    location: 'Alta Bates Summit Medical Center',
    administration: 'Hospital',
    medication: 'Albuterol',
    visit_time: '2024-01-29T03:50:52',
    duration: 68,
    medication_tolerance: 'Stable',
    pain_level: 2,
    blood_pressure: '145/92',
    nurse: {
      name: 'Robert Jones',
      profile_picture: 'https://api.dicebear.com/7.x/miniavs/svg?seed=14',
      specialty: 'Psychiatric',
    },
  },
];
